{% set name = "polap" %}
{% set version = "0.2.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ../../../../../polap/polap
  # url: https://github.com/goshng/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  # sha256: 5de2d8aeae3673e95c4d88c0bc2bf8f2061b346afb8c3261556b24cc0395f519

build:
  noarch: python
  number: 1

requirements:
  run:
    - python >=3.10.12
    - bioconda::flye >=2.9.2
    - bioconda::seqkit >=2.3.1
    - bioconda::minimap2 >=2.24
    - bioconda::blast >=2.12.0
    - bioconda::bedtools >=2.30.0
    - bioconda::seqtk >=1.3
    - bioconda::bioawk >=1.0
    - bioconda::entrez-direct >=15.6
    - bioconda::sra-tools >=3.0.0
    - bioconda::csvtk >=0.26.0
    - bioconda::gfastats >=1.3.6
    - bioconda::jellyfish >=2.2.10
    - bioconda::clustalw >=2.1
    - bioconda::samtools >=1.18
    - bioconda::assembly-stats >=1.0.1
    - bioconda::orthofinder >=2.5.5
    - bioconda::bioconductor-ggtree >=3.6.0
    - r-base >=4.3.2
    - conda-forge::r-dplyr >=1.1.4
    - conda-forge::r-readr >=2.1.5
    - conda-forge::r-optparse >=1.6.0
    - conda-forge::r-stringr >=1.3.1
    - conda-forge::r-tidyr >=1.3.1

test:
  commands:
    - polap -h

about:
  home: https://github.com/goshng/polap
  license: GPLv3
  license_family: GPL
  license_file: LICENSE
  summary: "POLAP: plant organelle long-read assembly pipeline"
  dev_url: https://github.com/goshng/polap
  doc_url: https://goshng.github.io/polap/polap.html

extra:
  recipe-maintainers:
    - Sang Chul Choi
