{% set name = "polap" %}
{% set version = "0.4.1.1" %}
{% set sha256 = "69d129846fc8b47a607fc894c199430deba0eed9011acc3e0ad3378f954149c0" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  url: https://github.com/goshng/{{ name }}/releases/download/0.4.1.1/polap-0.4.1.1.tar.gz
  sha256: "{{ sha256 }}"

build:
  noarch: generic
  number: 0
  entry_points:
    - cflye = cflye.main:main
  run_exports:
    - {{ pin_subpackage('polap', max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
  host:
    - python
    - pip
    - zlib
  run:
    - python
    - setuptools  # [osx and arm64]
    - flye >=2.9.2
    - minimap2 >=2.24
    - seqkit
    - bedtools
    - seqtk
    - csvtk
    - kmer-jellyfish
    - blast
    - entrez-direct
    - sra-tools
    - samtools
    - orthofinder
    - bioconductor-ggtree
    - networkx
    - pandas
    - gfatools
    - r-optparse
    - r-dplyr
    - r-readr
    - r-stringr
    - r-tidyr
    - r-taxize
    - r-rgbif
    - newick_utils
    - parallel
    - r-base
    - bioawk
    - assembly-stats
    - progressivemauve
    - clustalw
    - gfastats
    - perl-xml-libxml
    - icu
    - libxml2
    - perl
    - pandoc

test:
  commands:
    - python -c "import sys; print(sys.path)"
    - python -c "import cflye.main; print(cflye.main)"
    - cflye -h
    - polap

about:
  home: https://github.com/goshng/polap
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: "POLAP: plant organelle long-read assembly pipeline"
  dev_url: https://github.com/goshng/polap
  doc_url: https://goshng.github.io/polap/polap.html

extra:
  recipe-maintainers:
    - goshng
