argbash-init \
	--opt long-reads \
	--opt outdir \
	--opt short-read1 \
	--opt short-read2 \
	--opt sra \
	--opt unpolished-fasta \
	--opt final-assembly \
	--opt min-read-length \
	--opt threads \
	--opt coverage \
	--opt single-min \
	--opt-bool reduction-reads \
	--opt-bool contigger \
	--opt-bool all-annotate \
	--opt-bool use-edges \
	--opt-bool coverage-check \
	--opt-bool resume \
	--opt-bool circularize \
	--opt-bool step0 \
	--opt-bool step1 \
	--opt-bool step2 \
	--opt-bool step3 \
	--opt-bool step4 \
	--opt-bool step5 \
	--opt-bool step6 \
	--opt-bool step7 \
	--opt-bool step8 \
	--opt-bool step9 \
	--pos assemble \
	--separate \
	--separate \
	polap3.m4
