# This file is automatically generated by post-commit hook
# Commit hash: 30447d7
# Date (UTC): 2025-06-12T07:32:18Z
# Branch: main
# Tag: 0.4.3.7-binary

_polap_git_hash_version='30447d7'
_polap_git_date_utc='2025-06-12T07:32:18Z'
_polap_git_branch='main'
_polap_git_tag='0.4.3.7-binary'
