local _polap_var_ga="${ODIR}/${INUM}"
local MTCONTIGNAME="${_polap_var_ga}"/mt.contig.name-"${JNUM}"
local _polap_var_ga_annotation="${_polap_var_ga}/assembly_info_organelle_annotation_count.txt"
local _polap_var_ga_annotation_all="${_polap_var_ga}/assembly_info_organelle_annotation_count-all.txt"
local _polap_var_ga_annotation_table="${_polap_var_ga}/contig-annotation-table.txt"
local _polap_var_ga_annotation_depth_table="${_polap_var_ga}/contig-annotation-depth-table.txt"
local _polap_var_contigger="${_polap_var_ga}/30-contigger"
local _polap_var_contigger_gfa="${_polap_var_contigger}/graph_final.gfa"
local _polap_var_contigger_contigs_stats="${_polap_var_contigger}/contigs_stats.txt"
local _polap_var_contigger_contigs_fasta="${_polap_var_contigger}/contigs.fasta"
# assembly_contigs_stats="$FDIR"/30-contigger/contigs_stats.txt
# assembly_contigs_fasta="$FDIR"/30-contigger/contigs.fasta
local _polap_var_ann="${_polap_var_ga}"/50-annotation
local _polap_var_ann_CONTIGFILE="${_polap_var_ann}"/contig.fasta
local _polap_var_ann_CONTIGDB="${_polap_var_ann}"/contig
local _polap_var_ann_CONTIGNAME="${_polap_var_ann}"/contig.name
# MT
local _polap_var_ann_MTAABLAST="${_polap_var_ann}"/mtaa.blast
local _polap_var_ann_MTAABLASTBED="${_polap_var_ann}"/mtaa.blast.bed
local _polap_var_ann_MTAABED="${_polap_var_ann}"/mtaa.bed
local _polap_var_ann_MTGENECOUNT="${_polap_var_ann}"/mt.gene.count
# PT
local _polap_var_ann_PTAABLAST="${_polap_var_ann}"/ptaa.blast
local _polap_var_ann_PTAABLASTBED="${_polap_var_ann}"/ptaa.blast.bed
local _polap_var_ann_PTAABED="${_polap_var_ann}"/ptaa.bed
local _polap_var_ann_PTGENECOUNT="${_polap_var_ann}"/pt.gene.count
