name: polap
channels:
  - conda-forge
  - bioconda

dependencies:
  - python >=3.10.12
  - flye >=2.9.2
  - seqkit >=2.3.1
  - minimap2 >=2.24
  - blast >=2.12.0
  - bedtools >=2.30.0
  - seqtk >=1.3
  - bioawk >=1.0
  - entrez-direct >=15.6
  - sra-tools >=3.0.0
  - csvtk >=0.26.0
  - gfastats >=1.3.6
  - bioconda::kmer-jellyfish >=2.3.1
  - clustalw >=2.1
  - r-base >=4.3.2
  - conda-forge::r-dplyr >=1.1.4
  - conda-forge::r-readr >=2.1.5
  - conda-forge::r-optparse >=1.6.0
  - bioconda::samtools >=1.18
  - bioconda::assembly-stats >=1.0.1
  - bioconda::orthofinder >=2.5.5
  - conda-forge::r-stringr >=1.3.1
  - conda-forge::r-tidyr >=1.3.1
  - bioconda::bioconductor-ggtree >=3.6.0
  - conda-forge::networkx
  - conda-forge::pandas
