#!/usr/bin/env bash

################################################################################
# This file is part of polap.
#
# polap is free software: you can redistribute it and/or modify it under the 
# terms of the GNU General Public License as published by the Free Software 
# Foundation, either version 3 of the License, or (at your option) any later 
# version.
#
# polap is distributed in the hope that it will be useful, but WITHOUT ANY 
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR 
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with 
# polap. If not, see <https://www.gnu.org/licenses/>.
################################################################################

while read id
do
  esearch -db nuccore -query "$id[ACCN]" < /dev/null |\
    elink -target protein |\
    efetch -format fasta_cds_aa > aa/"$id".fa
  sleep 1
done < <(cat data/s16.txt)


