#!/usr/bin/env bash

################################################################################
# This file is part of polap.
#
# polap is free software: you can redistribute it and/or modify it under the 
# terms of the GNU General Public License as published by the Free Software 
# Foundation, either version 3 of the License, or (at your option) any later 
# version.
#
# polap is distributed in the hope that it will be useful, but WITHOUT ANY 
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR 
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with 
# polap. If not, see <https://www.gnu.org/licenses/>.
################################################################################

grep "contig_$1" -A 2 -B 9 o/70-filter/o/50-annotation/ptaa.blast.txt|grep "^Query="|cut -d' ' -f3-|cut -d'[' -f1|awk '{$1=$1};1'| sort|uniq
