#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
render_progress.py
Version: v0.7.0
SPDX-License-Identifier: GPL-3.0-or-later

Render one of four progress tables to a standalone HTML page:
  --type inputs | mt | pt | perf

Changes:
  - long-read total bases  (sum_len)           → show as Gb
  - actually used long-read bases (sum_len)    → show as Gb
  - net memory increase                       → show as Gb

Usage:
  python3 render_progress.py --json progress-report.json --type inputs --html-out progress-inputs.html
  python3 render_progress.py --json progress-report.json --type mt     --html-out progress-mt.html
  python3 render_progress.py --json progress-report.json --type pt     --html-out progress-pt.html
  python3 render_progress.py --json progress-report.json --type perf   --html-out progress-perf.html
"""

from __future__ import annotations
import argparse
import html
import json
import os
from typing import Any, Dict, List, Tuple

VERSION = "render_progress.py v0.7.0"


# ----------------------------- utilities -----------------------------


def safe_get(d: Dict[str, Any], path: List[str], default="NA") -> Any:
    cur = d
    for key in path:
        if not isinstance(cur, dict) or key not in cur:
            return default
        cur = cur[key]
    if cur in (None, "", []):
        return default
    return cur


def fmt(val: Any) -> str:
    return "NA" if val in (None, "", "NA") else str(val)


def make_species_link(species_folder: str, code: str) -> str:
    """
    Return an HTML hyperlink pointing to the species report page.

    Example:
        species_folder = 'Anthoceros_agrestis'
        returns: <a href="../../Anthoceros_agrestis/report-assemble.html">Aa01</a>
    """
    if not species_folder or species_folder == "NA":
        return html.escape(code)
    href = f"../../{species_folder}/report-assemble.html"
    return f'<a href="{html.escape(href)}">{html.escape(code)}</a>'


def html_page(
    title: str, header: List[str], rows: List[List[str]], meta: Dict[str, Any]
) -> str:
    info = f"Generated by {html.escape(VERSION)} • Source JSON version: {html.escape(meta.get('version',''))}"
    s: List[str] = []
    s.append("<!doctype html>")
    s.append('<html lang="en"><head>')
    s.append('<meta charset="utf-8">')
    s.append(f"<title>{html.escape(title)}</title>")
    s.append(
        """
<style>
body { font-family: system-ui, -apple-system, Segoe UI, Roboto, Ubuntu, Cantarell, Noto Sans, Helvetica, Arial, sans-serif; margin: 24px; }
h1 { margin: 0 0 .25rem 0; }
.meta { color: #555; font-size: 0.9rem; margin-bottom: 1rem; }
table { border-collapse: collapse; width: 100%; font-size: .95rem; }
th, td { border: 1px solid #ddd; padding: 6px 8px; text-align: left; }
thead th { background: #f5f5f7; position: sticky; top: 0; z-index: 1; }
tr:nth-child(even) { background: #fafafa; }
</style>
"""
    )
    s.append("</head><body>")
    s.append(f"<h1>{html.escape(title)}</h1>")
    s.append(f"<div class='meta'>{info}</div>")
    s.append("<table><thead><tr>")
    for h in header:
        s.append(f"<th>{html.escape(h)}</th>")
    s.append("</tr></thead><tbody>")

    # for r in rows:
    #     s.append("<tr>")
    #     for c in r:
    #         s.append(f"<td>{html.escape(str(c))}</td>")
    #     s.append("</tr>")

    for r in rows:
        s.append("<tr>")
        for c in r:
            cell = str(c)
            # Detect if already contains <a href=...> (our species link)
            if "<a href=" in cell:
                s.append(f"<td>{cell}</td>")  # already HTML, don't escape
            else:
                s.append(f"<td>{html.escape(cell)}</td>")
        s.append("</tr>")

    s.append("</tbody></table>")
    s.append("</body></html>")
    return "\n".join(s)


# ----------------------------- table builders -----------------------------


def build_rows_inputs(model: Dict[str, Any]) -> Tuple[List[str], List[List[str]]]:
    header = [
        "species-code",
        "long-read total bases (Gb)",
        "long-read read count (num_seqs)",
        "long-read AvgQual",
    ]
    rows: List[List[str]] = []
    for rec in model.get("species", []):
        code = fmt(rec.get("code_full"))
        sum_len_gb = fmt(
            safe_get(rec, ["reads_summary", "long", "sum_len_gb"])
        )  # converted in report JSON
        num_seqs = fmt(safe_get(rec, ["reads_summary", "long", "num_seqs"]))
        avgq = fmt(safe_get(rec, ["reads_summary", "long", "AvgQual"]))
        rows.append([code, sum_len_gb, num_seqs, avgq])
    return header, rows


def build_rows_mt(model: Dict[str, Any]) -> Tuple[List[str], List[List[str]]]:
    header = [
        "species-code",
        "long-read SRA accession",
        "long-read total bases (Gb)",
        "actually used long-read bases (Gb)",
        "mtDNA NCBI accession",
        "mtDNA NCBI sequence length",
        "polap mt (seq count)",
        "polap mt (total bases)",
        "elapsed time (polap)",
        "net memory increase Gb (polap)",
        "hostname",
    ]
    rows: List[List[str]] = []
    for rec in model.get("species", []):
        code = fmt(rec.get("code_full"))
        long_sra = fmt(safe_get(rec, ["sra", "long"]))
        total_long_gb = fmt(
            safe_get(rec, ["reads_summary", "long", "sum_len_gb"])
        )  # Gb
        used_long_gb = fmt(safe_get(rec, ["reads_used", "long", "sum_len_gb"]))  # Gb
        mt_acc = fmt(safe_get(rec, ["ncbi", "mt", "accession"]))
        mt_len = fmt(safe_get(rec, ["ncbi", "mt", "length"]))
        mt_count = fmt(safe_get(rec, ["polap", "mt", "seq_count"]))
        mt_total = fmt(safe_get(rec, ["polap", "mt", "total_bases"]))
        elapsed = fmt(safe_get(rec, ["summaries", "polap_assemble", "elapsed_hms"]))
        net_inc_gb = fmt(
            safe_get(rec, ["summaries", "polap_assemble", "net_increase_gb"])
        )  # Gb
        host = fmt(safe_get(rec, ["system", "hostname"]))
        # add hyperlink to the species folder's report page
        species_folder = fmt(safe_get(rec, ["paths", "species_dir"]))
        code_link = make_species_link(species_folder, code)

        rows.append(
            [
                code_link,  # clickable link
                long_sra,
                total_long_gb,
                used_long_gb,
                mt_acc,
                mt_len,
                mt_count,
                mt_total,
                elapsed,
                net_inc_gb,
                host,
            ]
        )

        # rows.append(
        #     [
        #         code,
        #         long_sra,
        #         total_long_gb,
        #         used_long_gb,
        #         mt_acc,
        #         mt_len,
        #         mt_count,
        #         mt_total,
        #         elapsed,
        #         net_inc_gb,
        #         host,
        #     ]
        # )
    return header, rows


def build_rows_pt(model: Dict[str, Any]) -> Tuple[List[str], List[List[str]]]:
    header = [
        "species-code",
        "long-read SRA accession",
        "long-read total bases (Gb)",
        "actually used long-read bases (Gb)",
        "ptDNA NCBI accession",
        "ptDNA NCBI sequence length",
        "polap pt (seq count)",
        "polap pt (total bases)",
    ]
    rows: List[List[str]] = []
    for rec in model.get("species", []):
        code = fmt(rec.get("code_full"))
        long_sra = fmt(safe_get(rec, ["sra", "long"]))
        total_long_gb = fmt(
            safe_get(rec, ["reads_summary", "long", "sum_len_gb"])
        )  # Gb
        used_long_gb = fmt(safe_get(rec, ["reads_used", "long", "sum_len_gb"]))  # Gb
        pt_acc = fmt(safe_get(rec, ["ncbi", "pt", "accession"]))
        pt_len = fmt(safe_get(rec, ["ncbi", "pt", "length"]))
        pt_count = fmt(safe_get(rec, ["polap", "pt", "seq_count"]))
        pt_total = fmt(safe_get(rec, ["polap", "pt", "total_bases"]))
        rows.append(
            [
                code,
                long_sra,
                total_long_gb,
                used_long_gb,
                pt_acc,
                pt_len,
                pt_count,
                pt_total,
            ]
        )
    return header, rows


def build_rows_perf(model: Dict[str, Any]) -> Tuple[List[str], List[List[str]]]:
    header = [
        "species-code",
        "species folder",
        "elapsed time (polap)",
        "net memory increase Gb (polap)",
        "disk used GB (polap)",
        "CPU model",
        "CPU cores",
        "hostname",
    ]
    rows: List[List[str]] = []
    for rec in model.get("species", []):
        code = fmt(rec.get("code_full"))
        species_folder = fmt(safe_get(rec, ["paths", "species_dir"]))
        elapsed = fmt(safe_get(rec, ["summaries", "polap_assemble", "elapsed_hms"]))
        net_inc_gb = fmt(
            safe_get(rec, ["summaries", "polap_assemble", "net_increase_gb"])
        )  # Gb
        disk_gb = fmt(safe_get(rec, ["summaries", "polap_assemble", "disk_used_gb"]))
        cpu_model = fmt(safe_get(rec, ["system", "cpu_model"]))
        cpu_cores = fmt(safe_get(rec, ["system", "cpu_cores"]))
        host = fmt(safe_get(rec, ["system", "hostname"]))
        rows.append(
            [
                code,
                species_folder,
                elapsed,
                net_inc_gb,
                disk_gb,
                cpu_model,
                cpu_cores,
                host,
            ]
        )
    return header, rows


# ----------------------------- main -----------------------------


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Render a progress table (inputs|mt|pt|perf) to HTML."
    )
    ap.add_argument(
        "--json", required=True, help="Aggregate JSON from report_progress.py"
    )
    ap.add_argument(
        "--type",
        required=True,
        choices=["inputs", "mt", "pt", "perf"],
        help="Which table to render",
    )
    ap.add_argument("--html-out", required=True, help="Output HTML path")
    ap.add_argument("--title", default=None, help="Optional page title")
    args = ap.parse_args()

    with open(args.json, "r", encoding="utf-8") as fh:
        model = json.load(fh)

    if args.type == "inputs":
        header, rows = build_rows_inputs(model)
        title = args.title or "Organelle Assembly Progress — Inputs"
    elif args.type == "mt":
        header, rows = build_rows_mt(model)
        title = args.title or "Organelle Assembly Progress — mtDNA"
    elif args.type == "pt":
        header, rows = build_rows_pt(model)
        title = args.title or "Organelle Assembly Progress — ptDNA"
    else:
        header, rows = build_rows_perf(model)
        title = args.title or "Organelle Assembly Progress — Performance"

    page = html_page(title, header, rows, meta=model.get("meta", {}))
    os.makedirs(os.path.dirname(os.path.abspath(args.html_out)), exist_ok=True)
    with open(args.html_out, "w", encoding="utf-8") as out:
        out.write(page)
    print(f"[OK] wrote {args.html_out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
