#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
render_progress.py
Version: v0.8.1
SPDX-License-Identifier: GPL-3.0-or-later

Render one of six progress artifacts to a standalone HTML page:
  --type inputs | mt | pt | perf | pt-png | mt-png

Tables:
  inputs: species-code, long-read total bases (Gb), read count, AvgQual
  mt:     species-code (link optional), long SRA, total bases (Gb), used bases (Gb),
          mt accession, mt length, polap mt (count/bases), elapsed time, net mem (Gb), hostname
  pt:     species-code (link optional), long SRA, total bases (Gb), used bases (Gb),
          pt accession, pt length, polap pt (count/bases)
  perf:   species-code, species folder, elapsed time, net mem (Gb), disk used (GB),
          CPU model, CPU cores, hostname

Galleries:
  pt-png: 5-column gallery of ../../<Species>/v6/0/polap-assemble/pt.1.png (species name caption)
  mt-png: 5-column gallery of ../../<Species>/v6/0/polap-assemble/mt.1.png (species name caption)

Usage examples:
  python3 render_progress.py --json progress-report.json --type inputs --html-out progress-inputs.html
  python3 render_progress.py --json progress-report.json --type mt     --html-out progress-mt.html
  python3 render_progress.py --json progress-report.json --type pt     --html-out progress-pt.html
  python3 render_progress.py --json progress-report.json --type perf   --html-out progress-perf.html
  python3 render_progress.py --json progress-report.json --type pt-png --html-out progress-pt-png.html
  python3 render_progress.py --json progress-report.json --type mt-png --html-out progress-mt-png.html
"""

from __future__ import annotations
import argparse
import html
import json
import os
from typing import Any, Dict, List, Tuple

VERSION = "render_progress.py v0.8.0"


# ----------------------------- utilities -----------------------------


def safe_get(d: Dict[str, Any], path: List[str], default="NA") -> Any:
    cur = d
    for key in path:
        if not isinstance(cur, dict) or key not in cur:
            return default
        cur = cur[key]
    if cur in (None, "", []):
        return default
    return cur


def fmt(val: Any) -> str:
    return "NA" if val in (None, "", "NA") else str(val)


def html_page_table(
    title: str, header: List[str], rows: List[List[str]], meta: Dict[str, Any]
) -> str:
    info = f"Generated by {html.escape(VERSION)} • Source JSON version: {html.escape(meta.get('version',''))}"
    s: List[str] = []
    s.append("<!doctype html>")
    s.append('<html lang="en"><head>')
    s.append('<meta charset="utf-8">')
    s.append(f"<title>{html.escape(title)}</title>")
    s.append(
        """
<style>
body { font-family: system-ui, -apple-system, Segoe UI, Roboto, Ubuntu, Cantarell, Noto Sans, Helvetica, Arial, sans-serif; margin: 24px; }
h1 { margin: 0 0 .25rem 0; }
.meta { color: #555; font-size: 0.9rem; margin-bottom: 1rem; }
table { border-collapse: collapse; width: 100%; font-size: .95rem; }
th, td { border: 1px solid #ddd; padding: 6px 8px; text-align: left; vertical-align: top; }
thead th { background: #f5f5f7; position: sticky; top: 0; z-index: 1; }
tr:nth-child(even) { background: #fafafa; }
td a { color: #0b5bd3; text-decoration: none; }
td a:hover { text-decoration: underline; }
</style>
"""
    )
    s.append("</head><body>")
    s.append(f"<h1>{html.escape(title)}</h1>")
    s.append(f"<div class='meta'>{info}</div>")
    s.append("<table><thead><tr>")
    for h in header:
        s.append(f"<th>{html.escape(h)}</th>")
    s.append("</tr></thead><tbody>")
    for r in rows:
        s.append("<tr>")
        for c in r:
            cell = str(c)
            # allow HTML links already formed (e.g., <a href="...">Aa01</a>)
            if "<a " in cell and "</a>" in cell:
                s.append(f"<td>{cell}</td>")
            else:
                s.append(f"<td>{html.escape(cell)}</td>")
        s.append("</tr>")
    s.append("</tbody></table>")
    s.append("</body></html>")
    return "\n".join(s)


def html_page_gallery(
    title: str, items: List[Tuple[str, str, str]], meta: Dict[str, Any]
) -> str:
    """
    items: list of (img_src, caption, link_href)
    Displays a 5-column grid with the species name above (left-aligned)
    and a gray placeholder if the image file is missing.
    """
    info = f"Generated by {html.escape(VERSION)} • Source JSON version: {html.escape(meta.get('version',''))}"
    s: List[str] = []
    s.append("<!doctype html>")
    s.append('<html lang="en"><head>')
    s.append('<meta charset="utf-8">')
    s.append(f"<title>{html.escape(title)}</title>")
    s.append(
        """
<style>
body {
  font-family: system-ui, -apple-system, Segoe UI, Roboto, Ubuntu, Cantarell, Noto Sans, Helvetica, Arial, sans-serif;
  margin: 24px; background: #fff;
}
h1 { margin: 0 0 .25rem 0; }
.meta { color: #555; font-size: 0.9rem; margin-bottom: 1rem; }
.grid { display: grid; grid-template-columns: repeat(5, 1fr); gap: 16px; }
.card {
  border: 1px solid #e3e3e3; border-radius: 8px; padding: 8px; background: #fff;
  box-shadow: 0 1px 2px rgba(0,0,0,0.05);
  display: flex; flex-direction: column; align-items: stretch;
}
.card .cap {
  margin-bottom: 6px; font-weight: 600; font-size: 0.95rem; color: #222; text-align: left;
}
.card .cap a { color: #0b5bd3; text-decoration: none; }
.card .cap a:hover { text-decoration: underline; }
.card img {
  width: 100%; height: auto; display: block; border-radius: 6px; border: 1px solid #f0f0f0;
}
.placeholder {
  width: 100%; aspect-ratio: 1 / 1; display: flex; align-items: center; justify-content: center;
  border-radius: 6px; background: #f6f6f6; color: #aaa; font-size: 0.95rem; border: 1px dashed #ddd;
}
@media (max-width: 1200px) { .grid { grid-template-columns: repeat(4, 1fr); } }
@media (max-width: 920px)  { .grid { grid-template-columns: repeat(3, 1fr); } }
@media (max-width: 680px)  { .grid { grid-template-columns: repeat(2, 1fr); } }
@media (max-width: 440px)  { .grid { grid-template-columns: repeat(1, 1fr); } }
</style>
"""
    )
    s.append("</head><body>")
    s.append(f"<h1>{html.escape(title)}</h1>")
    s.append(f"<div class='meta'>{info}</div>")
    s.append('<div class="grid">')

    # We'll need os.path here; import inline to keep this function drop-in.
    import os

    json_dir = (
        os.path.dirname(meta.get("json_path", ""))
        if meta.get("json_path")
        else os.getcwd()
    )

    for img_src, cap, link_href in items:
        s.append('<div class="card">')
        # Species name ABOVE the image, as a clickable link
        s.append(
            f'<div class="cap"><a href="{html.escape(link_href)}" target="_blank" rel="noopener">{html.escape(cap)}</a></div>'
        )
        abs_path = os.path.abspath(os.path.join(json_dir, img_src))
        if os.path.exists(abs_path):
            s.append(f'<img src="{html.escape(img_src)}" alt="{html.escape(cap)}">')
        else:
            s.append('<div class="placeholder">No assembly</div>')
        s.append("</div>")

    s.append("</div>")
    s.append("</body></html>")
    return "\n".join(s)


def make_species_link(species_folder: str, code: str) -> str:
    """
    Return an HTML hyperlink pointing to the species report page.
    Example:
        species_folder = 'Anthoceros_agrestis'
        returns: <a href="../../Anthoceros_agrestis/report-assemble.html">Aa01</a>
    """
    if not species_folder or species_folder == "NA":
        return html.escape(code)
    href = f"../../{species_folder}/report-assemble.html"
    return f'<a href="{html.escape(href)}">{html.escape(code)}</a>'


# ----------------------------- table builders -----------------------------


def build_rows_inputs(model: Dict[str, Any]) -> Tuple[List[str], List[List[str]]]:
    header = [
        "species-code",
        "long-read total bases (Gb)",
        "long-read read count (num_seqs)",
        "long-read AvgQual",
    ]
    rows: List[List[str]] = []
    for rec in model.get("species", []):
        code = fmt(rec.get("code_full"))
        sum_len_gb = fmt(safe_get(rec, ["reads_summary", "long", "sum_len_gb"]))  # Gb
        num_seqs = fmt(safe_get(rec, ["reads_summary", "long", "num_seqs"]))
        avgq = fmt(safe_get(rec, ["reads_summary", "long", "AvgQual"]))
        rows.append([code, sum_len_gb, num_seqs, avgq])
    return header, rows


def build_rows_mt(model: Dict[str, Any]) -> Tuple[List[str], List[List[str]]]:
    header = [
        "species-code",
        "long-read SRA accession",
        "long-read total bases (Gb)",
        "actually used long-read bases (Gb)",
        "mtDNA NCBI accession",
        "mtDNA NCBI sequence length",
        "polap mt (seq count)",
        "polap mt (total bases)",
        "elapsed time (polap)",
        "net memory increase Gb (polap)",
        "hostname",
    ]
    rows: List[List[str]] = []
    for rec in model.get("species", []):
        code = fmt(rec.get("code_full"))
        long_sra = fmt(safe_get(rec, ["sra", "long"]))
        total_long_gb = fmt(
            safe_get(rec, ["reads_summary", "long", "sum_len_gb"])
        )  # Gb
        used_long_gb = fmt(safe_get(rec, ["reads_used", "long", "sum_len_gb"]))  # Gb
        mt_acc = fmt(safe_get(rec, ["ncbi", "mt", "accession"]))
        mt_len = fmt(safe_get(rec, ["ncbi", "mt", "length"]))
        mt_count = fmt(safe_get(rec, ["polap", "mt", "seq_count"]))
        mt_total = fmt(safe_get(rec, ["polap", "mt", "total_bases"]))
        elapsed = fmt(safe_get(rec, ["summaries", "polap_assemble", "elapsed_hms"]))
        net_inc_gb = fmt(
            safe_get(rec, ["summaries", "polap_assemble", "net_increase_gb"])
        )  # Gb
        host = fmt(safe_get(rec, ["system", "hostname"]))
        species_folder = fmt(safe_get(rec, ["paths", "species_dir"]))
        code_link = make_species_link(species_folder, code)
        rows.append(
            [
                code_link,
                long_sra,
                total_long_gb,
                used_long_gb,
                mt_acc,
                mt_len,
                mt_count,
                mt_total,
                elapsed,
                net_inc_gb,
                host,
            ]
        )
    return header, rows


def build_rows_pt(model: Dict[str, Any]) -> Tuple[List[str], List[List[str]]]:
    header = [
        "species-code",
        "long-read SRA accession",
        "long-read total bases (Gb)",
        "actually used long-read bases (Gb)",
        "ptDNA NCBI accession",
        "ptDNA NCBI sequence length",
        "polap pt (seq count)",
        "polap pt (total bases)",
    ]
    rows: List[List[str]] = []
    for rec in model.get("species", []):
        code = fmt(rec.get("code_full"))
        long_sra = fmt(safe_get(rec, ["sra", "long"]))
        total_long_gb = fmt(
            safe_get(rec, ["reads_summary", "long", "sum_len_gb"])
        )  # Gb
        used_long_gb = fmt(safe_get(rec, ["reads_used", "long", "sum_len_gb"]))  # Gb
        pt_acc = fmt(safe_get(rec, ["ncbi", "pt", "accession"]))
        pt_len = fmt(safe_get(rec, ["ncbi", "pt", "length"]))
        pt_count = fmt(safe_get(rec, ["polap", "pt", "seq_count"]))
        pt_total = fmt(safe_get(rec, ["polap", "pt", "total_bases"]))
        species_folder = fmt(safe_get(rec, ["paths", "species_dir"]))
        code_link = make_species_link(species_folder, code)
        rows.append(
            [
                code_link,
                long_sra,
                total_long_gb,
                used_long_gb,
                pt_acc,
                pt_len,
                pt_count,
                pt_total,
            ]
        )
    return header, rows


def build_rows_perf(model: Dict[str, Any]) -> Tuple[List[str], List[List[str]]]:
    header = [
        "species-code",
        "species folder",
        "elapsed time (polap)",
        "net memory increase Gb (polap)",
        "disk used GB (polap)",
        "CPU model",
        "CPU cores",
        "hostname",
    ]
    rows: List[List[str]] = []
    for rec in model.get("species", []):
        code = fmt(rec.get("code_full"))
        species_folder = fmt(safe_get(rec, ["paths", "species_dir"]))
        elapsed = fmt(safe_get(rec, ["summaries", "polap_assemble", "elapsed_hms"]))
        net_inc_gb = fmt(
            safe_get(rec, ["summaries", "polap_assemble", "net_increase_gb"])
        )  # Gb
        disk_gb = fmt(safe_get(rec, ["summaries", "polap_assemble", "disk_used_gb"]))
        cpu_model = fmt(safe_get(rec, ["system", "cpu_model"]))
        cpu_cores = fmt(safe_get(rec, ["system", "cpu_cores"]))
        host = fmt(safe_get(rec, ["system", "hostname"]))
        rows.append(
            [
                code,
                species_folder,
                elapsed,
                net_inc_gb,
                disk_gb,
                cpu_model,
                cpu_cores,
                host,
            ]
        )
    return header, rows


# ----------------------------- gallery builders -----------------------------


def build_gallery_items(
    model: Dict[str, Any], which: str
) -> List[Tuple[str, str, str]]:
    """
    which: 'pt' or 'mt'
    Returns list of (img_src, caption, link_href),
      where link_href is '../../<Species>/report-assemble.html'.
    """
    items: List[Tuple[str, str, str]] = []
    for rec in model.get("species", []):
        species_folder = fmt(safe_get(rec, ["paths", "species_dir"]))
        species_name = fmt(rec.get("species"))
        if species_folder == "NA" or species_name == "NA":
            continue
        img_src = f"../../{species_folder}/v6/0/polap-assemble/{which}.1.png"
        link_href = f"../../{species_folder}/report-assemble.html"
        items.append((img_src, species_name, link_href))
    return items


# ----------------------------- main -----------------------------


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Render a progress table or gallery to HTML."
    )
    ap.add_argument(
        "--json", required=True, help="Aggregate JSON from report_progress.py"
    )
    ap.add_argument(
        "--type",
        required=True,
        choices=["inputs", "mt", "pt", "perf", "pt-png", "mt-png"],
        help="Which output to render",
    )
    ap.add_argument("--html-out", required=True, help="Output HTML path")
    ap.add_argument("--title", default=None, help="Optional page title")
    args = ap.parse_args()

    with open(args.json, "r", encoding="utf-8") as fh:
        model = json.load(fh)

    # Add json_path to meta for gallery file existence checks
    model.setdefault("meta", {})["json_path"] = args.json

    # Tables
    if args.type == "inputs":
        header, rows = build_rows_inputs(model)
        title = args.title or "Organelle Assembly Progress — Inputs"
        page = html_page_table(title, header, rows, meta=model.get("meta", {}))

    elif args.type == "mt":
        header, rows = build_rows_mt(model)
        title = args.title or "Organelle Assembly Progress — mtDNA"
        page = html_page_table(title, header, rows, meta=model.get("meta", {}))

    elif args.type == "pt":
        header, rows = build_rows_pt(model)
        title = args.title or "Organelle Assembly Progress — ptDNA"
        page = html_page_table(title, header, rows, meta=model.get("meta", {}))

    elif args.type == "perf":
        header, rows = build_rows_perf(model)
        title = args.title or "Organelle Assembly Progress — Performance"
        page = html_page_table(title, header, rows, meta=model.get("meta", {}))

    # Galleries
    elif args.type == "pt-png":
        items = build_gallery_items(model, "pt")
        title = args.title or "Organelle Assembly Gallery — ptDNA"
        page = html_page_gallery(title, items, meta=model.get("meta", {}))

    else:  # 'mt-png'
        items = build_gallery_items(model, "mt")
        title = args.title or "Organelle Assembly Gallery — mtDNA"
        page = html_page_gallery(title, items, meta=model.get("meta", {}))

    os.makedirs(os.path.dirname(os.path.abspath(args.html_out)), exist_ok=True)
    with open(args.html_out, "w", encoding="utf-8") as out:
        out.write(page)
    print(f"[OK] wrote {args.html_out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
